# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=1500]
      - id: check-merge-conflict
      - id: check-toml

#   - repo: https://github.com/astral-sh/ruff-pre-commit
#     rev: v0.12.5
#     hooks:
#       # Run the linter
#       - id: ruff-check
#         args: [--fix, --exit-non-zero-on-fix]
#       # Run the formatter
#       - id: ruff-format

#   - repo: local
#     hooks:
#       - id: update-revisions
#         name: Update all revisions
#         entry: python ./others/update_all_revisions.py
#         language: system
#         always_run: true
